// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbilxpqluuvxhmgfpggx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiaWx4cHFsdXV2eGhtZ2ZwZ2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTQyMzUsImV4cCI6MjA2ODY3MDIzNX0.uKxE_oSVGZXjeJpqlyzk23B-ld369SA1-gk5se9Fn8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});